model:
  base_learning_rate: 2.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    image_size: 64
    channels: 4
    monitor: val/loss_simple_ema

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 4
        out_channels: 4
        model_channels: 128
        attention_resolutions:
        # note: this isn\t actually the resolution but
        # the downsampling factor, i.e. this corresnponds to
        # attention on spatial resolution 8,16,32, as the
        # spatial reolution of the latents is 64 for f4
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 8
        num_head_channels: 8
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 4
        n_embed: 8192
        #ckpt_path: logs/2024-04-09T10-35-16_autoencoder_kl_64x64x3_mvtec/checkpoints/last.ckpt
        #ckpt_path: logs/2024-04-10T20-44-28_autoencoder_kl_64x64x1_mvtec/checkpoints/last.ckpt
        ckpt_path: logs/2024-04-11T19-24-39_vqgan_f8_mvtec/checkpoints/last.ckpt
        ddconfig:
          double_z: False
          z_channels: 4
          resolution: 256
          in_channels: 1
          out_ch: 1
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: [32]
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
      
    cond_stage_config: __is_unconditional__

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 10
    wrap: false
    train:
      target: taming.data.custom_test.CustomTrain_crop
      params:
        image_folder: /home/aurelie/datasets/mvtec_anomaly/screw/mini_train
        size: 1024
    validation:
      target: taming.data.custom_test.CustomTest_crop
      params:
        image_folder: /home/aurelie/datasets/mvtec_anomaly/screw/val
        size: 1024


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 100
        max_images: 100
        increase_log_steps: False

  trainer:
    benchmark: True
    gpus: 1
   

    #precision: 16
    #scaler: GradScaler
    
    
